#!/usr/bin/env node

const path = require('path')
const fs = require('fs')

// Simple script to set up database environment for local development
console.log('\x1b[32m✅ Using local SQLite database at prisma/dev.db\x1b[0m')
console.log('   Tip: delete prisma/dev.db to reset the simulation data.')

// Set environment variable for SQLite with ABSOLUTE PATH to prevent duplicates
const projectRoot = path.resolve(__dirname, '..')
const dbPath = path.join(projectRoot, 'prisma', 'dev.db')
const databaseUrl = `file:${dbPath}`

process.env.DATABASE_URL = databaseUrl
console.log(`   📍 Absolute path: ${dbPath}`)

// Write to .env.local to ensure Prisma Client uses the absolute path
const envLocalPath = path.join(projectRoot, '.env.local')
const envContent = `# ============================================================================
# AUTO-GENERATED LOCAL DEVELOPMENT DATABASE CONFIG
# ============================================================================
#
# WICHTIG: Diese Datei wird AUTOMATISCH von scripts/select-db.js generiert!
#
# - Diese Datei wird in .gitignore ignoriert (nicht im Git)
# - Sie wird bei jedem \`npm run dev\` automatisch erstellt/aktualisiert
# - Sie überschreibt die .env Datei für lokale Entwicklung
#
# NIEMALS MANUELL EDITIEREN!
# - Wenn du Development startest, wird diese Datei überschrieben
# - Alle manuellen Änderungen gehen verloren
#
# WIE ES FUNKTIONIERT:
# - \`npm run dev\` → ruft select-db.js → setzt SQLite
# - Lokale Datenbank: prisma/dev.db (absolute path)
# - Um die DB zurückzusetzen: \`rm prisma/dev.db\` und neu starten
#
# ============================================================================

# This file is auto-generated by scripts/select-db.js
# Last updated: ${new Date().toISOString()}
DB_SOURCE=sqlite
DATABASE_URL="${databaseUrl}"
DIRECT_URL="${databaseUrl}"
`

fs.writeFileSync(envLocalPath, envContent, 'utf8')
console.log(`   ✅ Updated .env.local with absolute database path`)
